---
- name: install tomcat9
  hosts: db
  become: yes

  tasks:

  - name: Enshure JDK 11 package is present
    apt:
      name: openjdk-11-jdk
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory      

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true


- name: install OpenJdk, Maven
  hosts: web
  become: yes

  tasks:
  
  - name: Update and upgrade apt packages
    apt:
      upgrade: dist
  
  - name: Ensure Maven package is present
    apt:
      name: maven
      state: present

  - name: downloading the repository from GitHub
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse-sample-java-war-hello

  - name: building WAR file in Maven
    shell: mvn --file /tmp/boxfuse-sample-java-war-hello/pom.xml package

  - name: copy artifact to prod machine
    become: yes
    synchronize:
      mode: pull
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /opt/tomcat/webapps/
    delegate_to: 34.136.36.44