---
- name: install OpenJdk, Maven
  hosts: web
  become: yes

  tasks:
  - name: Ensure Openjdk package is present
    apt: 
      name: OpenJdk-11-jdk
      state: present
  
  - name: Ensure Maven package is present
    apt:
      name: maven
      state: present

  - name: downloading the repository from GitHub
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/

  - name: building WAR file in Maven
    shell:
      command: mvn -f /tmp/boxfuse-sample-java-war-hello/pom.xml package