---
- name: install tomcat9
  hosts: db
  become: yes

  tasks:
  
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Ensure Openjdk package is present
    apt: 
      name: openjdk-11-jdk
      state: present
    
  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: start tomcat
    script: "/opt/tomcat/bin/catalina.sh start"

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true


- name: install OpenJdk, Maven
  hosts: web
  become: yes

  tasks:

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Ensure Maven package is present
    apt:
      name: maven
      state: present

  - name: downloading the repository from GitHub
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/

  - name: building WAR file in Maven
    shell:
      command: mvn -f /tmp/boxfuse-sample-java-war-hello/pom.xml package

  - name: copy artifact to prod machine
    synchronize:
      mode: pull
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /opt/tomcat/webapps/
    delegate_to: db
